Install minor fix

diff --git a/install b/install
--- a/install
+++ b/install
@@ -66,7 +66,7 @@ cp ~/.local/share/applications/pipewire-controller.desktop ~/.config/autostart/p
 # Execute and echo success or error message
 echo "💡 Launching Pipewire Controller..."
 sleep 1
-$APP_PATH || echo "❌ Failed to launch the application. Try running 'pipewire-controller' manually."
+$APP_PATH & > /dev/null & || echo "❌ Failed to launch the application. Try running 'pipewire-controller' manually."
 
 echo "✅ Installation complete!"
 echo "💡 You can now find 'Pipewire Controller' in your Application Menu."
